### PR TITLE
Ensure pinning latest channel to nixpkgs nixos-unstable branch

### PR DESCRIPTION
**Pull request by teutat3s**

### CODE REVIEW

**Comment by blaggacao** [comment]
bors try

**Comment by blaggacao** [comment]
bors try

**Comment by blaggacao** [comment]
bors try

**Comment by teutat3s** [comment]
bors try

**Comment by teutat3s** [comment]
I've forced pushed the commit to only contain the lockfile change for the `latest` input

**Comment by blaggacao** [comment]
bors try
bosrs delegate+

**Review by blaggacao — APPROVED** [review]

**Pull request merged**
