### PR TITLE
suites: simplify code

### PR DESCRIPTION
**Pull request by blaggacao**
If this code had been written this way, I wouldn't have opened #200 in
the first place. (perspective of a begginer nix-langer)

closes: #200 This is a pre-fix to PR #202

### CODE REVIEW

**Comment by Pacman99** [comment]
This makes defining suites much more complex. You have to call profileMap at the front of every suite.

**Comment by blaggacao** [comment]
> This makes defining suites much more complex. You have to call profileMap at the front of every suite.

But at least I do understand what I'm actually doing :wink:

**Comment by blaggacao** [comment]
bors try+

**Comment by blaggacao** [comment]
bors try

**Comment by blaggacao** [comment]
bors try-

I think I still don't understand what this code does.

**Comment by Pacman99** [comment]
>profileMap implements the receiving end of the fs layout contract. Now everything is clear by analogy / parallelism with allProfiles & allUsers.

I think proper ux and a stable api is more important than an analogy being correct. And having users run a function on every suite manually, imo, is a step backwards. And if you just look down at the mapAttrs, you would see that profileMap is run at every function. So I really don't see what this PR accomplishes.

**Comment by blaggacao** [comment]
ping, made a change.

The commit message has the impetus (me in abstractable role of nix beginner trying to understand what's going on).

**Comment by blaggacao** [comment]
bors try

**Comment by blaggacao** [comment]
This code produces a `segfault`. Whooo :waffle: 

```
/nix/store/vf2f1xph3v6afy0bx0cf46bp82qincpy-devshell-dir/bin/flk: line 28: 300128 Segmentation fault      (core dumped) nix build "$DEVSHELL_ROOT#nixosConfigurations.$2.config.system.build.iso" "${@:3}
```

I was thinking it would have been equivalent.

**Pull request closed without merging**
