### PR TITLE
Update flake to use new modules options

### PR DESCRIPTION
**Pull request by Pacman99**
connected to divnix/digga#107

### CODE REVIEW

**Review by GTrunSec — APPROVED** [review]

**Comment by GTrunSec** [comment]
It works for me.
- nix develop --command -- check-downstream

**Comment by Pacman99** [comment]
bors try

**Comment by FlorianFranzen** [comment]
I would be nice to see this merged, as it blocks the update to the latest `digga` release, e.g. as need to fix #376.

**Review by nrdxp — APPROVED** [review]

**Comment by nrdxp** [comment]
bor r+

**Pull request merged**
