### PR TITLE
remove anti-corruption layer

### PR DESCRIPTION
**Pull request by Sohalt**
https://github.com/NixOS/nix/pull/4641 got merged, so this should probably be safe to remove? @blaggacao

### CODE REVIEW

**Comment by blaggacao** [comment]
bord try

**Comment by blaggacao** [comment]
Let's see... :-)

**Comment by teutat3s** [comment]
This section already got removed in #403, this PR now looks obsolete to me.

**Comment by Pacman99** [comment]
Closing since #403 included this change. Thanks for the PR!

**Pull request closed without merging**
