### PR TITLE
Update inputs and switch back to pulling devos as a template

### PR DESCRIPTION
**Pull request by Pacman99**

### CODE REVIEW

**Comment by Pacman99** [comment]
bors try

**Comment by Pacman99** [comment]
bors try

**Comment by Pacman99** [comment]
bors try

**Review by blaggacao — APPROVED** [review]

**Comment by blaggacao** [comment]
bors +

**Comment by Pacman99** [comment]
I think when it tries to pull some hm file from the cache its failing. The "unexpected end of file" indicates a cache issue according to a nix issue. Which is why it works the first time when that files gets built, but not the second time when it gets pulled from the cache.

**Comment by Pacman99** [comment]
Going to merge since the build succeeded the first time and nothing has changed since then. We should try to figure out whats going on with the cache configuration and the CI

**Pull request merged**
