### PR TITLE
develop

### PR DESCRIPTION
**Pull request by blaggacao**
- init: common flake compat fixes for other nixpkgs
- ref: pass our lib as lib.our to the module system
- bump digga to latest develop
- bump: nixpkgs to avoid https://github.com/NixOS/nixpkgs/pull/127720
- feature: Add pkgs fetch manager nvfetcher
- doc: nvfetcher
- fix hasekllPackages overlay
- core: use bottom instead of gotop
- ref: move devshell module here to `devos` again
- work-around for https://github.com/NixOS/nix/pull/4641
- fix: hm pin to corresponding nixos version
- imp: reduce flake inputs footprint and increase conciseness
- fix: bump digga with infinite recursion hotfix
- imp: add portable user definition
- rm: community
- ref: make hm common module explicit
- bump: pull in latest bud fixes & additions
- bump: point to tip of squashed digga develop branch

### CODE REVIEW

**Comment by blaggacao** [comment]
bors try

**Comment by blaggacao** [comment]
bors try

**Comment by codygman** [comment]
Hm, I just tested this one and it still has the direnv flake support issue it looks like:

```
devos  core took 40s 
✖1 ❯ git log --oneline -n1
73431f5 (HEAD -> core, origin/core, origin/HEAD) rm: community

devos  core 
❯ git status
On branch core
Your branch is up to date with 'origin/core'.

nothing to commit, working tree clean

devos  core 
❯ direnv allow
direnv: loading ~/org-roam/data/6f/b938fb-323f-4e27-b508-fed7b80c22f2/devos/.envrc
direnv: using flake
error: 'print-dev-env' is not a recognised command
Try '/nix/store/h3s9yqj1jzcl0vaxndn12alc98373vh7-nix-2.3.14/bin/nix --help' for more information.
error: 'flake' is not a recognised command
Try '/nix/store/h3s9yqj1jzcl0vaxndn12alc98373vh7-nix-2.3.14/bin/nix --help' for more information.
direnv: renewed cache
direnv: export ~XDG_DATA_DIRS

devos  core 
❯ direnv --version
2.28.0

```

**Comment by blaggacao** [comment]
So w.r.t hm, I think we would be looking at: https://github.com/nix-community/home-manager/blob/b39647e52ed3c0b989e9d5c965e598ae4c38d7ef/modules/programs/direnv.nix#L79 &mdash; is that correct?

> It also looks like the default generated flk up has an issue:

A.f.a.i.u., this should have been solved via https://github.com/divnix/bud/commit/35830a146481cb3ab0713b59a143cbd0e9b93767

`develop` is a bit of unchartered territory, but on the other hand `core` has fallen quite some bit behind. And in addition to that, we still don't have cut a release with the `digga` changes. :disappointed:

**Comment by blaggacao** [comment]
So `main` is the new `develop` and also the default branch (soonish)

**Comment by codygman** [comment]
No problem, glad to test. I'll try moving over to main and testing things out.

Thanks for all the hard work!

**Pull request closed without merging**
