### PR TITLE
home-manager fixes

### PR DESCRIPTION
**Pull request by nrdxp**
- [x] integrate nix-community/home-manager#1880 (to avoid duplicate commits, we'll wait a bit to see if this gets merged)
- [x] don't use all of `systemPackages` for `flk home` 
- [x] test home-manager `activationPackage` and `flk home` as part of CI

### CODE REVIEW

**Comment by Pacman99** [comment]
Also considering that this issue wasn't caught originally, perhaps add the activationPackage for nixos user to checks.

**Comment by Pacman99** [comment]
If none of the hm PR's get merged soon you could also use the `extraSpecialArgs` option to fix the issue. That way no change in home-manager upstream is required. Since devos always sets `useGlobalPackages` that would be an okay fix.

**Comment by nrdxp** [comment]
Ready for preliminary review.

**Review by Pacman99 — APPROVED** [review]

**Pull request merged**
