### PR TITLE
chore: update deploy-rs, nvfetcher, devshell

### PR DESCRIPTION
**Pull request by GTrunSec**
- waiting for https://github.com/divnix/digga/pull/108

### CODE REVIEW

**Comment by nrdxp** [comment]
this is great, but I'd love to do this is CI say once a week or so.

**Comment by GTrunSec** [comment]
that would be good. Here same idea for updating pkgs automatically. https://github.com/divnix/devos/pull/352/commits/8f1a70f641abd596705b32627c1a309a2c6d6cdd

**Review by Pacman99 — APPROVED** [review]
LGTM, I'm not sure if something needs to be done before merge for this
bors delegate+

**Comment by GTrunSec** [comment]
bors try

**Review by nrdxp — APPROVED** [review]
bors r+

**Pull request merged**
