### PR TITLE
iso: copy input closourse into iso to avoide re-download

### LINKED ISSUE #190: pin inputs into iso live registry
## Would your feature fix an existing issue?
With #168 , devos live iso gains the ability to enter the devos devshell and install through it on the target machine during bootstrapping.

Still, the target machine is fetching all inputs again.

## Describe the solution you'd like
By pinning inputs into the registry:
- the target will probably use them (if lockfile is not present and declares a different sha)
- more importantly, the nix store closures will get copied over (I hope I'm right?) and therefore there is no deed to fetch those files

## Describe alternatives you've considered
n/a

## Additional context
- Suggested by @Pacman99 https://github.com/divnix/devos/pull/168#issuecomment-800420441
- similarily, we might want to find a way to copy the devshell closure to the iso, so that entering the devshell uses the baked in nix store closure.

### PR DESCRIPTION
**Pull request by blaggacao**
closes #190

Tested on my setup, considerably cuts times and only leaves one (noticable) download.

### CODE REVIEW

**Comment by blaggacao** [comment]
@Pacman99 I tested this locally and it already works more than great. Thank you for the idea! Do you know how we could copy the devshell closure, too? Currently, the devshell seems to be the only remaining thing that is unecesarily built on the target machine.

**Comment by blaggacao** [comment]
bors try

**Comment by Pacman99** [comment]
ohh wait I actually haven't tested that code locally, I just wrote the code out. But it should be simple enough to build the isoConfig and inspect the result.

**Comment by blaggacao** [comment]
> ohh wait I actually haven't tested that code locally, I just wrote the code out. But it should be simple enough to build the isoConfig and inspect the result.

I fully tried end to end and it works.

`nix registry list` shows all those local store paths.

Maybe we need to filter out the ones that are `flake = false, though`? or handle them differently? What do you think?

**Comment by Pacman99** [comment]
Yeah you could, but it really wouldn't make much of a difference. Worst case theres just one unnecessary folder in the nix store.

**Comment by blaggacao** [comment]
> Yeah you could, but it really wouldn't make much of a difference. Worst case theres just one unnecessary folder in the nix store.

Ok, let's don't bother then. That path might even be useful on the iso under some odd circumstances.

**Comment by Pacman99** [comment]
So I'm not sure about this. But perhaps we could not import all modules of the system and just selectively pass along parts of the configuration. This would prevent starting up unnecessary system services while still adding necessary dependencies.

I think this would involve evaluating the modules in a seperate `nixosSystem` call. And just passing along some things. 

for example:
```nix
environment = { inherit (system.config.environment) systemPackages; };
```

**Comment by blaggacao** [comment]
> So I'm not sure about this. But perhaps we could not import all modules of the system and just selectively pass along parts of the configuration. This would prevent starting up unnecessary system services while still adding necessary dependencies.

Do you refer to your previous suggestion to not enable all _modules_?

This PR is meant (and restrained to) specifically to target #190. I'll open an issue for that.

**Comment by Pacman99** [comment]
Yeah its just another idea. Doesn't have to be a part of this PR.

**Comment by blaggacao** [comment]
x-ref: https://github.com/divnix/devos/issues/194

**Comment by nrdxp** [comment]
if it's ready, go ahead and merge
bors delegate+

**Review by nrdxp — APPROVED** [review]
LGTM

**Comment by blaggacao** [comment]
I suspect that it actually does _not_ cache evaluations, since the commands still take some time in silence, that is no command output (which I only can explain with evaluation)?

Can those evaluations, like [this](https://hercules-ci.com/accounts/github/divnix/derivations/%2Fnix%2Fstore%2Fpncxk7zpm8vp4242g9413hsy6869y5i3-devshell.drv?via-job=ed571c00-c5a5-4ca8-a8af-719f2843302f), for example, also be copied into the store?

**Review by Pacman99 — APPROVED** [review]

**Pull request merged**
